version: '3'

services:
  database:
    image: mysql:5.7
    volumes:
      - db_volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=itemsdatabase
      - MYSQL_USER =root
      - MYSQL_PASSWORD =root
    ports:
      - 3306:3306
  backend:
    build:
      context: './backend'
    depends_on:
      - database
    ports:
      - 8000:8000
  frontend:
    build:
      context: './FrontEnd'
    depends_on:
      - backend
  proxy:
    build:
      context: ./Proxy
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
volumes:
  db_volume: